branches:
  - main
  - name: release-*
    prerelease: true
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/github"
    - assets:
        - "build/discv4-crawl"
  - "@semantic-release/git"
